### ISSUE TITLE
Second report does not render correctly

### ISSUE THREAD

**Issue by martincostello** [Tyrrrz/GitHubActionsTestLogger#22]
### Version

2.2.0

### Details

After updating to 2.2.0, if more than one test project is included in a GitHub Actions workflow where other content is also written to the step summary, the title of the second test run report does not render correctly.

Attached are two screenshots showing the rendering before and after the change.

### Before

![IMG_0451](https://github.com/Tyrrrz/GitHubActionsTestLogger/assets/1439341/7a68f454-bf0f-4e7e-b977-50ab17655c60)

[Workflow](https://github.com/justeattakeaway/httpclient-interception/actions/runs/5000186842)

### After

![IMG_0452](https://github.com/Tyrrrz/GitHubActionsTestLogger/assets/1439341/b270098c-93c2-44ed-9bfe-8477a1850717)

### Steps to reproduce

Clone https://github.com/justeattakeaway/httpclient-interception/pull/565/commits/3274754bdfd8413dc6d2e8ba221800abefbc74c4 and run `build.ps1` in GitHub Actions.

**Comment by martincostello** [comment]
An option to opt-in to retaining the collapsible behaviour from previous versions would be nice also. In the case where there’s multiple reports and other content, like the above examples, it looks a bit neater IMHO.

**Comment by Tyrrrz** [comment]
Thanks for the report @martincostello, I've pushed a new version. It was caused by the coverage summary not ending in two newlines to reset the markdown parser back to markdown mode (from HTML).

As for the option: yeah, that's something to consider. The new layout is significantly different due to test grouping, so it will be hard to switch between them seamlessly, though. It's really difficult to make things look nice with just markdown, especially when the data is very dynamic in nature.
